### Weather Disaster Prediction 
#### DS 3000 Final Project
Members: Luke Abbatessa, Daniel Gilligan, Ruby Potash, Megan Putnam

**Data Information**

Data set: https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/

Datasets include three types of data related to weather events recorded for a given year: 
1. Storm details
2. Fatalities
3. Locations 

Naming convention for the csv files are as follows: "StormEvents_[file_type]-ftp_v1.0_d[data_year]_c[creation_date].csv.gz"

Consulted the related data dictionary for assistance throughout the project
https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/Storm-Data-Bulk-csv-Format.pdf

Consulted stack overflow for NotJSONError 
https://stackoverflow.com/questions/32103772/unreadable-notebook-notjsonerrornotebook-does-not-appear-to-be-json-u-n#:~:text=An%20easy%20way%20to%20check%20errors%20in%20json,open%20the%20nb%20again%20as%20usual%20%E2%80%93%20Lucas

In [1]:
# Import necessary libraries
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [2]:
# Set data paths and columns of interest

LOCATIONS_2021 = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2021_c20221116.csv.gz"
DETAILS_2021 = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2021_c20221116.csv.gz"
FATALITIES_2021 = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2021_c20221116.csv.gz"

LOCATIONS_2020 = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2020_c20220816.csv.gz"
DETAILS_2020 = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2020_c20220816.csv.gz"
FATALITIES_2020 = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2020_c20220816.csv.gz"

LOCATIONS_2019 = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_locations-ftp_v1.0_d2019_c20220425.csv.gz"
DETAILS_2019 = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_details-ftp_v1.0_d2019_c20220425.csv.gz"
FATALITIES_2019 = "https://www.ncei.noaa.gov/pub/data/swdi/stormevents/csvfiles/StormEvents_fatalities-ftp_v1.0_d2019_c20220425.csv.gz"

COLS_OF_INTEREST = [
    "BEGIN_YEARMONTH", "END_YEARMONTH", "EVENT_TYPE", "CZ_TYPE", "EPISODE_NARRATIVE", 
    "EVENT_NARRATIVE", "INJURIES_DIRECT", "DEATHS_DIRECT", "DAMAGE_PROPERTY", "DAMAGE_CROPS", 
    'TOR_F_SCALE','TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO', 'TOR_OTHER_CZ_STATE',
    'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME'
]

In [3]:
# Helper functions 

def merge_dfs(df1, df2, col):
    """Merge two dataframes on a common column"""
    joined_df = pd.merge(df1, df2, on=col)
    return joined_df

def year_data_import(loc_csv, detail_csv, fatal_csv, merge_on="EVENT_ID"): 
    """Returns df of merged location, detail, and fatalities csv files 
    for a given year (default is merge on event ID)"""
    loc_df = pd.read_csv(loc_csv)
    detail_df = pd.read_csv(detail_csv)
    fatal_df = pd.read_csv(fatal_csv)
    
    loc_detail_df = merge_dfs(loc_df, detail_df, merge_on)
    joined_df = merge_dfs(loc_detail_df, fatal_df, merge_on)
    
    return joined_df

def missing_data_eval(df, include_col='all'): 
    """Evaluates missing data by row and columns for given dataframe and prints output.
    Specify list of columns to include in include_col, otherwise will include all"""
    if include_col != 'all':
        df = df[include_col]  # specify subset to evaluate 
        
    print("Shape:", df.shape)
    print("\nData missing per col:", df.isnull().sum().sort_values(ascending=False), sep="\n")
    print("\nNumber of rows (right) missing X columns (left)):", df.isnull().sum(axis=1).value_counts(), sep="\n")
    
def change_col_types(df, col, data_type):
    """Change column data types as necessary"""
    df[col] = df[col].astype(data_type)
    return df[col]

def split_date(df, date_col_name, new_names):
    """Splits yearmonth column into separate year and month columns.
    Returns updated df with given naming convention 
    (new_names: list in order of year, month col names)"""
    df[new_names[0]] = df[date_col_name].str[:4]
    df[new_names[1]] = df[date_col_name].str[4:]
    return df

def get_unique_col_vals(df):
    """Gather unique values from each dataframe column"""
    for col in df:
        print(df[col].unique())
        
def identify_data_dims(df):
    """Investigate the dimensions of a dataframe"""
    data_dims = df.shape
    return data_dims
    
def perform_deletion(df):
    """Delete rows with missing variables""" 
    df = df.dropna()
    return df

Consulted Statistics Globe to confirm the process of merging two Pandas DataFrames
https://statisticsglobe.com/merge-pandas-dataframes-based-on-particular-column-python#:~:text=Within%20this%20function%2C%20we%20have%20to%20specify%20the,on%20%3D%20%22col%22%29%20print%28data_join%29%20%23%20Print%20merged%20DataFrame

In [4]:
# Merge data type files for each year and concatenate into on df

df_2021 = year_data_import(LOCATIONS_2021, DETAILS_2021, FATALITIES_2021)
df_2020 = year_data_import(LOCATIONS_2020, DETAILS_2020, FATALITIES_2020)
df_2019 = year_data_import(LOCATIONS_2019, DETAILS_2019, FATALITIES_2019)

joined_df = pd.concat([df_2021, df_2020, df_2019])  # merge into one df

display(joined_df)

,YEARMONTH,EPISODE_ID_x,EVENT_ID,LOCATION_INDEX,RANGE,AZIMUTH,LOCATION,LATITUDE,LONGITUDE,LAT2,...,FAT_YEARMONTH,FAT_DAY,FAT_TIME,FATALITY_ID,FATALITY_TYPE,FATALITY_DATE,FATALITY_AGE,FATALITY_SEX,FATALITY_LOCATION,EVENT_YEARMONTH
0,202102,155272,936331,1,2.96,SSW,KAHAKULOA,20.9611,-156.5692,2057666,...,202102,18,0,42429,I,02/18/2021 00:00:00,26.0,F,In Water,202102
1,202102,155272,936331,2,1.58,N,KIPAHULU,20.6725,-156.0739,2040350,...,202102,18,0,42429,I,02/18/2021 00:00:00,26.0,F,In Water,202102
2,202102,155279,936389,1,1.60,NW,WAIHEE,20.9455,-156.5385,2056730,...,202102,27,0,42430,I,02/27/2021 00:00:00,27.0,M,In Water,202102
3,202102,155279,936389,1,1.60,NW,WAIHEE,20.9455,-156.5385,2056730,...,202102,27,0,42431,I,02/27/2021 00:00:00,NaN,M,In Water,202102
4,202102,155279,936389,2,1.01,NNW,KIPAHULU,20.6640,-156.0743,2039840,...,202102,27,0,42430,I,02/27/2021 00:00:00,27.0,M,In Water,202102
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613,201906,139903,841676,1,0.66,W,WILSONVILLE,38.1216,-85.4119,387296,...,201906,17,0,39315,D,06/17/2019 00:00:00,40.0,M,Vehicle/Towed Trailer,201906
614,201906,139903,841676,2,0.77,WNW,WILSONVILLE,38.1228,-85.4138,387368,...,201906,17,0,39315,D,06/17/2019 00:00:00,40.0,M,Vehicle/Towed Trailer,201906
615,201906,139903,841676,3,0.86,W,WILSONVILLE,38.1216,-85.4156,387296,...,201906,17,0,39315,D,06/17/2019 00:00:00,40.0,M,Vehicle/Towed Trailer,201906
616,201906,139903,841676,4,0.79,W,WILSONVILLE,38.1208,-85.4145,387248,...,201906,17,0,39315,D,06/17/2019 00:00:00,40.0,M,Vehicle/Towed Trailer,201906
617,201907,140378,843943,1,1.73,SE,CRESTVIEW,41.6100,-83.6500,4136600,...,201907,2,0,39355,D,07/02/2019 00:00:00,35.0,M,Vehicle/Towed Trailer,201907

In [5]:
# Evaluate missing data counts for columns of interest and rows 
missing_data_eval(joined_df, include_col=COLS_OF_INTEREST)

Shape: (1869, 17)

Data missing per col:
TOR_OTHER_CZ_NAME     1591
TOR_OTHER_CZ_FIPS     1591
TOR_OTHER_CZ_STATE    1591
TOR_OTHER_WFO         1591
TOR_F_SCALE           1443
TOR_WIDTH             1443
TOR_LENGTH            1443
DAMAGE_PROPERTY        211
DAMAGE_CROPS            86
EVENT_NARRATIVE          2
END_YEARMONTH            0
DEATHS_DIRECT            0
INJURIES_DIRECT          0
EPISODE_NARRATIVE        0
CZ_TYPE                  0
EVENT_TYPE               0
BEGIN_YEARMONTH          0
dtype: int64

Number of rows (right) missing X columns (left)):
7    1400
1     156
0     114
4     112
9      30
6      18
5      18
8      13
2       8
dtype: int64

Missing data shows that tornado specific feature columns ("TOR_\*")are missing from many of the records, due to not being applicable for event type. Property damage and crop damage variables are only other features of interest missing values.

In [6]:
# Filter the joined dataframe based on the columns of interest
filtered_df = joined_df[COLS_OF_INTEREST]
display(filtered_df.head(5))

print(filtered_df.dtypes)

,BEGIN_YEARMONTH,END_YEARMONTH,EVENT_TYPE,CZ_TYPE,EPISODE_NARRATIVE,EVENT_NARRATIVE,INJURIES_DIRECT,DEATHS_DIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,TOR_OTHER_WFO,TOR_OTHER_CZ_STATE,TOR_OTHER_CZ_FIPS,TOR_OTHER_CZ_NAME
0,202102,202102,Heavy Rain,C,"A surface front stalled near Kauai, along with...",A 26-year-old woman died when she was swept ou...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,202102,202102,Heavy Rain,C,"A surface front stalled near Kauai, along with...",A 26-year-old woman died when she was swept ou...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,202102,202102,Heavy Rain,C,Gusty trade winds helped keep showers moving a...,Two hikers went missing along the Waikamoi Tra...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,202102,202102,Heavy Rain,C,Gusty trade winds helped keep showers moving a...,Two hikers went missing along the Waikamoi Tra...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,202102,202102,Heavy Rain,C,Gusty trade winds helped keep showers moving a...,Two hikers went missing along the Waikamoi Tra...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN

BEGIN_YEARMONTH         int64
END_YEARMONTH           int64
EVENT_TYPE             object
CZ_TYPE                object
EPISODE_NARRATIVE      object
EVENT_NARRATIVE        object
INJURIES_DIRECT         int64
DEATHS_DIRECT           int64
DAMAGE_PROPERTY        object
DAMAGE_CROPS           object
TOR_F_SCALE            object
TOR_LENGTH            float64
TOR_WIDTH             float64
TOR_OTHER_WFO          object
TOR_OTHER_CZ_STATE     object
TOR_OTHER_CZ_FIPS     float64
TOR_OTHER_CZ_NAME      object
dtype: object

Consulted stack overflow for making a new column from the string slice of another
https://stackoverflow.com/questions/25789445/pandas-make-new-column-from-string-slice-of-another-column

In [7]:
# Change BEGIN_YEARMONTH and END_YEARMONTH from objects to strings to allow for slicing
dtype_dict = {"BEGIN_YEARMONTH":pd.StringDtype(), "END_YEARMONTH": pd.StringDtype()}
filtered_df = filtered_df.astype(dtype_dict)

# Separate BEGIN_YEARMONTH and END_YEARMONTH into year and month columns
filtered_df = split_date(filtered_df, "BEGIN_YEARMONTH", ["BEGIN_YEAR", "BEGIN_MONTH"]) 
filtered_df = split_date(filtered_df, "END_YEARMONTH", ["END_YEAR", "END_MONTH"]) 

# Drop the now-unnecessary columns BEGIN_YEARMONTH and END_YEARMONTH
filtered_df = filtered_df.drop(["BEGIN_YEARMONTH", "END_YEARMONTH"], axis=1)

print(filtered_df.columns)
display(filtered_df.head(5))

Index(['EVENT_TYPE', 'CZ_TYPE', 'EPISODE_NARRATIVE', 'EVENT_NARRATIVE',
       'INJURIES_DIRECT', 'DEATHS_DIRECT', 'DAMAGE_PROPERTY', 'DAMAGE_CROPS',
       'TOR_F_SCALE', 'TOR_LENGTH', 'TOR_WIDTH', 'TOR_OTHER_WFO',
       'TOR_OTHER_CZ_STATE', 'TOR_OTHER_CZ_FIPS', 'TOR_OTHER_CZ_NAME',
       'BEGIN_YEAR', 'BEGIN_MONTH', 'END_YEAR', 'END_MONTH'],
      dtype='object')

,EVENT_TYPE,CZ_TYPE,EPISODE_NARRATIVE,EVENT_NARRATIVE,INJURIES_DIRECT,DEATHS_DIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,TOR_OTHER_WFO,TOR_OTHER_CZ_STATE,TOR_OTHER_CZ_FIPS,TOR_OTHER_CZ_NAME,BEGIN_YEAR,BEGIN_MONTH,END_YEAR,END_MONTH
0,Heavy Rain,C,"A surface front stalled near Kauai, along with...",A 26-year-old woman died when she was swept ou...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,02,2021,02
1,Heavy Rain,C,"A surface front stalled near Kauai, along with...",A 26-year-old woman died when she was swept ou...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,02,2021,02
2,Heavy Rain,C,Gusty trade winds helped keep showers moving a...,Two hikers went missing along the Waikamoi Tra...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,02,2021,02
3,Heavy Rain,C,Gusty trade winds helped keep showers moving a...,Two hikers went missing along the Waikamoi Tra...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,02,2021,02
4,Heavy Rain,C,Gusty trade winds helped keep showers moving a...,Two hikers went missing along the Waikamoi Tra...,0,0,0.00K,0.00K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021,02,2021,02

In [8]:
# Change the types of certain columns
dtype_dict = {"EVENT_TYPE":pd.StringDtype(), 
              "CZ_TYPE": pd.StringDtype(), 
              "EPISODE_NARRATIVE":pd.StringDtype(), 
              "EVENT_NARRATIVE":pd.StringDtype(),
              "TOR_F_SCALE":pd.StringDtype(), 
              "TOR_LENGTH":float, 
              "TOR_WIDTH":float,
              "TOR_OTHER_WFO":pd.StringDtype(),
              "TOR_OTHER_CZ_STATE":pd.StringDtype(), 
              "TOR_OTHER_CZ_FIPS":float, 
              "TOR_OTHER_CZ_NAME":pd.StringDtype(),
              "BEGIN_YEAR":int,
              "BEGIN_MONTH":int,
              "END_YEAR":int,
              "END_MONTH":int}

filtered_df = filtered_df.astype(dtype_dict)
print(filtered_df.dtypes)

EVENT_TYPE             string
CZ_TYPE                string
EPISODE_NARRATIVE      string
EVENT_NARRATIVE        string
INJURIES_DIRECT         int64
DEATHS_DIRECT           int64
DAMAGE_PROPERTY        object
DAMAGE_CROPS           object
TOR_F_SCALE            string
TOR_LENGTH            float64
TOR_WIDTH             float64
TOR_OTHER_WFO          string
TOR_OTHER_CZ_STATE     string
TOR_OTHER_CZ_FIPS     float64
TOR_OTHER_CZ_NAME      string
BEGIN_YEAR              int64
BEGIN_MONTH             int64
END_YEAR                int64
END_MONTH               int64
dtype: object

In [9]:
# Clean property damage and crop damage columns to convert to numeric data 
# Replace "K" with (3 zeros - 2), "M" with (6 - 2), 
# "B" with (9 - 2), and "." with "" for DAMAGE_PROPERTY and DAMAGE_CROPS
# 
# Already 2 0's after a decimal point for both columns
letter_num = {"K": "0"*(3-2), "M": "0"*(6-2), "B": "0"*(9-2), ".": ""}
    
filtered_df["DAMAGE_PROPERTY"] \
= filtered_df["DAMAGE_PROPERTY"].str.translate(str.maketrans(letter_num))

filtered_df["DAMAGE_PROPERTY"] = pd.to_numeric(filtered_df["DAMAGE_PROPERTY"])

filtered_df["DAMAGE_CROPS"] \
= filtered_df["DAMAGE_CROPS"].str.translate(str.maketrans(letter_num))

filtered_df["DAMAGE_CROPS"] = pd.to_numeric(filtered_df["DAMAGE_CROPS"])

        
get_unique_col_vals(filtered_df)  # get unique column values for df

<StringArray>
[              'Heavy Rain',                'Lightning',
              'Flash Flood',                  'Tornado',
        'Thunderstorm Wind',       'Marine Strong Wind',
                    'Flood',              'Debris Flow',
                     'Hail', 'Marine Thunderstorm Wind']
Length: 10, dtype: string
<StringArray>
['C', 'Z']
Length: 2, dtype: string
<StringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                        'A surface front stalled near Kauai, along with an upper trough, brought heavy rain and thunderstorms to parts of the Aloha State, and flash flooding to Kauai.  Downpours over windward East Maui during this episode contributed to the death of a 26-year-old woman who was swept out to sea when Waioka Pond near Hana became swollen by waters coming down the slope from near the Haleakala summit.  The costs of any damages were not available.',
                                                                                                                                                                                                                                                                                                                                                               'Gusty trade winds helped keep showers moving as an upper trough induced downpours from the Big Island to Oahu.  The precipitation caused ponding on roadways, and small stream and drainage ditch flooding.  Also, two hikers were killed in East Maui on the 27th, apparently after being swept over a falls along Waikamoi Trail into the sea.  The body of one hiker had been found as of this writing, but the other was still unaccounted for.  There were no significant damages reported.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            'Light southwesterly flow coupled with abundant moisture brought widespread showers and storms to West Central Florida. Unfortunately, one of those thunderstorms produced a fatal lightning strike.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'A cold front moved in and stalled while multiple upper level disturbances moved through. High moisture levels and ample lift provided a few days of flooding and severe thunderstorms.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'A tornado that touched down in Jefferson County during the morning of October 16,2021 crossed into Millstone Township in western Elk County, producing EF-1 damage in Elk County. The tornado had estimated peak winds of 90 mph, a path length of just over 0.6 miles, and a maximum path width of 260 yards.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           'Post Tropical Cyclone Ida brought heavy rain to New Jersey on September 1.  Rainfall totals were as high as 5 to 10 inches.  The heavy rain caused significant flash flooding, mainly in the northern half of the state.  It resulted in widespread property damage.  There were several fatalities.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              'Strong low-level shear and marginal instability ahead of a strong cold front sweeping through the region combined to produce a few strong to severe thunderstorms, and an tornado, across parts of north Georgia.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             'Post Tropical Cyclone Ida brought heavy rain to eastern Pennsylvania on September 1.  Rainfall totals were as high as 5 to 10 inches.  The heavy rain caused significant flash flooding, mainly in the southeastern part of the state.  It resulted in widespread property damage.  There were several fatalities.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     'The month of May started with a bang as a low pressure system moved through the Intermountain West, producing thunderstorms with severe winds, dust storms and small hail.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Showers and thunderstorms repeatedly moved across Northern Madison and into Western Jackson Counties during the mid-morning hours, lingering into the afternoon hours on the 19th. Numerous flooding reports were received as 3-5 of rainfall occurred, resulting in 1 fatality in Northern Madison County.',
 ...
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                'Scattered thunderstorms developed near the Georgia and South Carolina Blue Ridge during the afternoon and moved southeast. Some of the storms formed into small clusters and produced locally damaging wind gusts. One of these gusts resulted in fatalities in Pickens County.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          'Thunderstorms brought 2 to around 5.5 inches of rain to parts of southeastern Pennsylvania on the afternoon and evening of July 11.  The heaviest of the rain fell in southeastern Berks County, northern Chester County and upper Montgomery County.',
                                                                                               'Multiple rounds of thunderstorms moved across eastern Oklahoma from the afternoon of June 22nd through the early morning hours of the 24th, as a cold front approached the area from the west. The strongest storms produced damaging wind and large hail up to quarter size. In addition, widespread two to four inches of rain occurred across the area, with some areas receiving between five and seven inches during that period. Flash flooding resulted from this excessive rain. The widespread, heavy rainfall also resulted in moderate flooding of the Neosho River near Commerce, the Spring River near Quapaw, the Illinois River near Watts, Chewey, and Tahlequah, the Arkansas River near Muskogee, and the Poteau River near Poteau and Panama.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         'Lightning struck some people at the Lawshe Plantation.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'Afternoon thunderstorms produced localized gusty winds across Citrus County knocking down trees in the area. Additionally, 8 people on Clearwater Beach were struck by lightning by a developing thunderstorm.',
                                                                                                                                                                                                                                                                                                                                                                                                                                             'A large Mesoscale Convective System (MCS) formed over Missouri early in the day. By evening, a line of severe storms had made its way into Kentucky and sounthern Indiana. This line continued south and southeast through Kentucky causing widespread damage and a loss of life. In the end, 3 tornadoes were confirmed with many other reports of downed trees, severe hail, property damage, and power outages.',
 'Scattered monsoon thunderstorms, some with intense rainfall, developed across portions of southern Gila County during the evening hours on July 22nd. Some of the stronger storms produced peak rainfall rates well in excess of one inch per hour; the heavy rain caused flash flooding around and to the northeast of the town of Globe, along and to the west of highway 77. Due to the very heavy rain, a Flash Flood Warning was issued at 1828MST. Shortly after the warning was issued, the public reported water flowing over Glendale Avenue in Central Heights.  Unfortunately, despite the warning being issued well in advance, at 1750MST two adults in a pickup truck crossing Irene Gulch were swept away by floodwaters. One was rescued but the other perished. The fatality occurred about 3 miles to the northeast of the town of Claypool.',
                                                                                                                                                                                                    'Low pressure over west central Indiana moved slowly east in Ohio on the afternoon and evening of the 21st. The boundary slowed to a stationary front across central Ohio, becoming a catalyst for storm development. Rainfall rates of 2 to inches an hour occurred in the heaviest rainfall. The Weather Prediction Center highlighted an area along the US 30 corridor across central Ohio for a heightened risk of flash flooding.  Thunderstorms increased in coverage and intensity around 4 PM lasting into the evening. Flash flooding occurred along a line from Wyandot to Mahoning Counties where rainfall amounts of 2 to 5 inches of rain fell.',
                                                                                                   'Between June 17-19, the Ohio Valley sat in a warm moist environment with a stationary front draped from northeast to southwest across Indiana and on through Texas. Little wind shear existed above central Kentucky. This provided several days where diurnal heating and shortwave forcing kicked off pulse storms with high rainfall rates. After a few days of this, the ground became more saturated and flooding became easier with each event. ||On June 17th in Spencer County, A 40 year old man was traveling across a low water cross while the water level was elevated due to recent rainfall. The vehicle and the occupants were pushed into the creek. A woman and two children made it to safety, but the victim was found later downstream.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                  'Numerous severe thunderstorms produced widespread wind damage and locally severe microbursts across northern Ohio. The atmospheric conditions were very favorable for microbursts and wind damage that afternoon and evening. Downward CAPE values were extremely high and the upper air profiles shows an Inverted-V sounding. Some of the hardest hit areas were around Milan southward to the Canton area.']
Length: 366, dtype: string
<StringArray>
[                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       'A 26-year-old woman died when she was swept out to sea after the place where she was swimming near Hana became swollen by rainwater that had fallen over the upper slopes of Haleakala.',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 'Two hikers went missing along the Waikamoi Trail in East Maui.  As of this writing, the body of one hiker had been found, apparently swept out to sea over a waterfall in the area.  The other hiker remained unaccounted for, but he likely perished as well.',

In [10]:
# Filter the df by tornadoes, and gauge the missing values in the tornado df
tornado_df = filtered_df[filtered_df["EVENT_TYPE"] == "Tornado"]
display(tornado_df.head(5))

missing_data_eval(tornado_df)

,EVENT_TYPE,CZ_TYPE,EPISODE_NARRATIVE,EVENT_NARRATIVE,INJURIES_DIRECT,DEATHS_DIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,TOR_OTHER_WFO,TOR_OTHER_CZ_STATE,TOR_OTHER_CZ_FIPS,TOR_OTHER_CZ_NAME,BEGIN_YEAR,BEGIN_MONTH,END_YEAR,END_MONTH
14,Tornado,C,A tornado that touched down in Jefferson Count...,An EF-1 tornado was confirmed to have occurred...,1,1,20000.0,0.0,EF1,0.58,260.0,<NA>,<NA>,NaN,<NA>,2021,10,2021,10
15,Tornado,C,A tornado that touched down in Jefferson Count...,An EF-1 tornado was confirmed to have occurred...,1,1,20000.0,0.0,EF1,0.58,260.0,<NA>,<NA>,NaN,<NA>,2021,10,2021,10
150,Tornado,C,The remnants of Hurricane Ida impacted the mid...,A semi-discrete supercell thunderstorm began t...,2,1,5000000.0,0.0,EF2,8.28,400.0,<NA>,<NA>,NaN,<NA>,2021,9,2021,9
151,Tornado,C,The remnants of Hurricane Ida impacted the mid...,A semi-discrete supercell thunderstorm began t...,2,1,5000000.0,0.0,EF2,8.28,400.0,<NA>,<NA>,NaN,<NA>,2021,9,2021,9
154,Tornado,C,A very moist and moderately unstable airmass o...,A National Weather Service survey determined t...,0,0,20000000.0,NaN,EF4,21.72,1850.0,FFC,GA,113.0,FAYETTE,2021,3,2021,3

Shape: (426, 19)

Data missing per col:
DAMAGE_PROPERTY       178
TOR_OTHER_WFO         148
TOR_OTHER_CZ_NAME     148
TOR_OTHER_CZ_FIPS     148
TOR_OTHER_CZ_STATE    148
DAMAGE_CROPS           48
EVENT_TYPE              0
END_YEAR                0
BEGIN_MONTH             0
BEGIN_YEAR              0
TOR_LENGTH              0
TOR_WIDTH               0
CZ_TYPE                 0
TOR_F_SCALE             0
DEATHS_DIRECT           0
INJURIES_DIRECT         0
EVENT_NARRATIVE         0
EPISODE_NARRATIVE       0
END_MONTH               0
dtype: int64

Number of rows (right) missing X columns (left)):
1    156
0    114
4    112
6     18
5     18
2      8
dtype: int64

In [11]:
# Perform deletion and observe tornado_df's dimensions 
# before and after
initial_dims = identify_data_dims(tornado_df)
print("Below are the initial dimensions of tornado_df.")
print(initial_dims)
print(" ")

tornado_df = perform_deletion(tornado_df)
final_dims = identify_data_dims(tornado_df)
print("Below are the dimensions of tornado_df after "
      "missing values are deleted.")
print(final_dims)
print(" ")

print("After deletion,", initial_dims[0] - final_dims[0], "rows "
      "were removed from the data.")

Below are the initial dimensions of tornado_df.
(426, 19)

Below are the dimensions of tornado_df after missing values are deleted.
(114, 19)

After deletion, 312 rows were removed from the data.